### ISSUE TITLE
Bug in regularization for data with >1 feature

### ISSUE THREAD

**Issue by csheare** [benibaeumle/Learning-Shapelets#1]
Hi I am trying to run the demo model with regularization on a new dataset that is shape (1200,165,144), with samples being 1200 features being 165, and timepoints being 144. When I sub in my data for the demo code (without normalization), I get the following message: "t() expects a tensor with <= 2 dimensions, but self is 3D". I suspect this is due to the number of features being >1. To test this, I took 1 feature of my data (ie data[:,0:1,:]) and the code works (although not a great accuracy!).

Code block that yields the error:

```
losses_acc = []
losses_dist = []
losses_sim = []
train_acc_last_Lr = 0
for _ in range(n_epoch_steps):
    losses_acc_i, losses_dist_i, losses_sim_i = \
        learning_shapelets_Lr.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,
                                  shuffle=shuffle, drop_last=drop_last)
    losses_acc += losses_acc_i
    losses_dist += losses_dist_i
    losses_sim += losses_sim_i
    train_acc_current_Lr = eval_accuracy(learning_shapelets_Lr, X_train, y_train)
    if train_acc_current_Lr - train_acc_last_Lr < 1e-3 or train_acc_current_Lr == 1.0:
        break
    train_acc_last_Lr = train_acc_current_Lr
```

**Comment by benibaeumle** [comment]
Hi Courtney
I forgot to implement the calculation for the cosine similarity (for the L_ss regularizer) in case you have multivariate data. I just updated it. I implemented it by calculating the cosine similarities channel-wise and averaging over the channels. I am not sure how to better handle that. In case you are not comfortable with that, you can deactivate that loss term simply by keeping l2=0.0.

Can you confirm that you can run it now on your data?

Best,
Beni
